- hosts: elk_master_nodes
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.10.0
    es_enable_xpack: false
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_java_install: true
    es_heap_size: "1g"
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: ["10.5.5.12:9300"] #replace with the ip adress of the master node
      discovery.seed_hosts: ["10.5.5.12:9300","10.5.3.115:9300","10.5.0.101:9300"] #replace with ip adresses of different nodes. 
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
     - plugin: ingest-attachment

- hosts: elk_data_nodes
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.10.0
    es_enable_xpack: false
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_java_install: true
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: ["10.5.5.12:9300"] #replace with the ip adress of the master node
      discovery.seed_hosts: ["10.5.5.12:9300","10.5.3.115:9300","10.5.0.101:9300"] #replace with ip adresses of different nodes. 
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
      - plugin: ingest-attachment
